# Generated by Django 5.1.3 on 2024-12-11 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Name'},
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('phone', 'phone'), ('computer', 'computer')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='photos/2024/12/09/Screenshot_2024-11-08_132430.png', upload_to='photos/%Y/%m/%d/', verbose_name='photos'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='hala', max_length=100),
        ),
    ]
