# Generated by Django 5.1.3 on 2024-12-11 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateField(),
        ),
    ]
