# Generated by Django 5.1.3 on 2024-12-11 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_female_alter_test_created_male'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='male',
            name='girls',
        ),
        migrations.DeleteModel(
            name='Female',
        ),
        migrations.DeleteModel(
            name='Male',
        ),
    ]
